# Generated by Django 5.0.7 on 2024-08-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='resident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='users.resident'),
        ),
        migrations.AlterField(
            model_name='block',
            name='residence_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='residence.residence'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='block_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='residence.block'),
        ),
    ]
