# Generated by Django 5.1 on 2024-09-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='residence_id',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unit_no', 'block')},
        ),
        migrations.AddField(
            model_name='block',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='residence.residence'),
        ),
        migrations.AddField(
            model_name='unit',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='residence.block'),
        ),
        migrations.AddField(
            model_name='unit',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='users.resident'),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='block_id',
        ),
    ]
