# Generated by Django 5.1 on 2024-09-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0002_unit_resident_id_alter_block_residence_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='resident_id',
            new_name='resident',
        ),
    ]
