# Generated by Django 5.1 on 2024-09-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0003_rename_resident_id_unit_resident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='block_id',
            new_name='block',
        ),
    ]
