# Generated by Django 5.1 on 2024-09-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0004_rename_block_id_unit_block'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unit_no', 'block')},
        ),
    ]
