# Generated by Django 5.1 on 2024-09-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0005_alter_unit_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='residence_id',
            new_name='residence',
        ),
    ]
