# Generated by Django 5.1 on 2024-10-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # Define the dependencies required for this migration to run
    dependencies = [
        ('users', '0001_initial'),  # Assuming users app has initial migration
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[
                    ('Received', 'Received'), 
                    ('In Progress', 'In Progress'), 
                    ('Resolved', 'Resolved'), 
                    ('Rejected', 'Rejected')
                ], default='Received', max_length=20)),
                ('date', models.DateField()),
                ('complaint_created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.resident')),
            ],
        ),
    ]
