# Generated by Django 5.1 on 2024-11-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial_squashed_0003_complaint_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
