# Generated by Django 5.1 on 2024-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_add_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, choices=[('Facility', 'Facility'), ('Payment', 'Payment'), ('Bookings', 'Bookings'), ('Services', 'Services'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
