# Generated by Django 5.1 on 2024-09-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_deleted',
        ),
    ]
