# Generated by Django 5.1 on 2024-09-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_parking_created_at_parking_created_at_and_more'),
        ('users', '0004_feedback'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='car_place_no',
            new_name='car_plate_no',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='parking_id',
        ),
        migrations.AddField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='users.resident'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_parking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_visitor', to='parking.visitorparking'),
        ),
    ]
