# Generated by Django 5.0.7 on 2024-08-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='car_place_no',
            new_name='car_plate_no',
        ),
    ]
