# Generated by Django 5.1 on 2024-09-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('visitor', '0002_rename_car_place_no_visitor_car_plate_no'), ('visitor', '0003_visitor_resident'), ('visitor', '0004_remove_visitor_parking_id_visitor_visitor_parking'), ('visitor', '0005_alter_visitor_resident_alter_visitor_visitor_parking')]

    dependencies = [
        ('users', '0004_feedback'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='car_place_no',
            new_name='car_plate_no',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='parking_id',
        ),
        migrations.AddField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resident'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_parking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_visitor', to='parking.visitorparking'),
        ),
    ]
