# Generated by Django 5.1 on 2024-10-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('visitor', '0002_alter_visitor_check_in_time_and_more'), ('visitor', '0003_alter_visitor_check_in_date'), ('visitor', '0004_alter_visitor_check_out_date_squashed_0005_alter_visitor_check_in_time')]

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='check_in_time',
            field=models.TimeField(null=True),
        ), #change to timefield
        migrations.AlterField(
            model_name='visitor',
            name='check_in_date',
            field=models.DateField(),
        ), #change to datefield

        #same for checking out
        migrations.AlterField(
            model_name='visitor',
            name='check_out_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='check_out_date',
            field=models.DateField(null=True),
        ),

    ]
