# Generated by Django 5.1 on 2024-09-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedback'),
        ('visitor', '0002_rename_car_place_no_visitor_car_plate_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(default='default_string', on_delete=django.db.models.deletion.CASCADE, to='users.resident'),
            preserve_default=False,
        ),
    ]
