# Generated by Django 5.1 on 2024-09-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_visitorparking_visitor'),
        ('visitor', '0003_visitor_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='parking_id',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_parking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_visitor', to='parking.visitorparking'),
        ),
    ]
