# Generated by Django 5.0.7 on 2024-08-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('resident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_feedback', to='users.resident')),
            ],
        ),
    ]
