# Generated by Django 5.1 on 2024-09-18 14:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('booking_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.datetime(2024, 9, 18, 22, 42, 30, 618601))),
                ('end_time', models.TimeField(default=datetime.datetime(2024, 9, 18, 22, 42, 30, 618601))),
            ],
        ),
        migrations.CreateModel(
            name='FacilitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bookings.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Sections',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.resident')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.facilitysection')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.timeslot')),
            ],
            options={
                'unique_together': {('section', 'booking_date', 'time_slot')},
            },
        ),
    ]
