# Generated by Django 5.1 on 2024-09-18 14:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='facility_type',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.resident'),
        ),
        migrations.AddField(
            model_name='facility',
            name='booking_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 18, 22, 15, 53, 186131)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 18, 22, 15, 53, 186131)),
        ),
        migrations.CreateModel(
            name='FacilitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bookings.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Sections',
            },
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.facilitysection'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('section', 'booking_date', 'time_slot')},
        ),
        migrations.DeleteModel(
            name='FacilityType',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
