# Generated by Django 5.1 on 2024-09-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='capacity',
            new_name='total_units',
        ),
    ]
