# Generated by Django 5.1 on 2024-09-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_capacity_facility_total_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='facility_type',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='resident',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='total_units',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default='default_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='booking_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default='default end time'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FacilitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bookings.facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Sections',
            },
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='section',
            field=models.ForeignKey(default='default section', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.facilitysection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('section', 'booking_date', 'time_slot')},
        ),
        migrations.DeleteModel(
            name='FacilityType',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='facility',
        ),
    ]
