# Generated by Django 5.1 on 2024-09-18 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residence', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parkings', to='residence.block')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resident_parkings', to='parking.parking')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resident_parkings', to='users.resident')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitor_parkings', to='parking.parking')),
            ],
        ),
    ]
