# Generated by Django 5.1 on 2024-09-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('residence', '0001_initial'),
        ('users', '0004_feedback'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='parking_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='parking_deleted_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='parking_updated_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='residentparking',
            name='parking_id',
        ),
        migrations.RemoveField(
            model_name='residentparking',
            name='resident_id',
        ),
        migrations.RemoveField(
            model_name='residentparking',
            name='slot_no',
        ),
        migrations.RemoveField(
            model_name='visitorparking',
            name='parking_id',
        ),
        migrations.RemoveField(
            model_name='visitorparking',
            name='slot_no',
        ),
        migrations.AddField(
            model_name='parking',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parkings', to='residence.block'),
        ),
        migrations.AddField(
            model_name='parking',
            name='parking_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentparking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentparking',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resident_parkings', to='parking.parking'),
        ),
        migrations.AddField(
            model_name='residentparking',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resident_parkings', to='users.resident'),
        ),
        migrations.AddField(
            model_name='visitorparking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorparking',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitor_parkings', to='parking.parking'),
        ),
        migrations.AddField(
            model_name='visitorparking',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitors_parkings', to='visitor.visitor'),
        ),
        migrations.AddIndex(
            model_name='parking',
            index=models.Index(fields=['parking_no'], name='parking_par_parking_bd66bb_idx'),
        ),
    ]
