# Generated by Django 5.0.7 on 2024-08-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('residence', '0001_initial'),
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parkings', to='residence.block'),
        ),
        migrations.AlterField(
            model_name='residentparking',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_parkings', to='parking.parking'),
        ),
        migrations.AlterField(
            model_name='residentparking',
            name='resident_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_parkings', to='users.resident'),
        ),
        migrations.AlterField(
            model_name='visitorparking',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking', to='parking.parking'),
        ),
    ]
