# Generated by Django 5.1 on 2024-09-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parking_block_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='parking_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='parking_deleted_at',
            new_name='deleted_at',
        ),
    ]
