# Generated by Django 5.1 on 2024-09-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_rename_parking_updated_at_parking_updated_at'),
        ('residence', '0005_alter_unit_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='block_id',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='residentparking',
            old_name='parking_id',
            new_name='parking',
        ),
        migrations.RenameField(
            model_name='residentparking',
            old_name='resident_id',
            new_name='resident',
        ),
        migrations.RemoveField(
            model_name='residentparking',
            name='slot_no',
        ),
        migrations.RemoveField(
            model_name='visitorparking',
            name='parking_id',
        ),
        migrations.RemoveField(
            model_name='visitorparking',
            name='slot_no',
        ),
        migrations.AddField(
            model_name='parking',
            name='parking_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentparking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorparking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorparking',
            name='parking',
            field=models.ForeignKey(default='default_string', on_delete=django.db.models.deletion.PROTECT, related_name='visitor_parkings', to='parking.parking'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='parking',
            index=models.Index(fields=['parking_no'], name='parking_par_parking_bd66bb_idx'),
        ),
    ]
