# Generated by Django 5.1 on 2024-09-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_rename_block_id_parking_block_and_more'),
        ('visitor', '0003_visitor_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorparking',
            name='visitor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='visitors_parkings', to='visitor.visitor', null=True),
            preserve_default=False,
        ),
    ]
