# Generated by Django 5.1 on 2024-09-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_visitorparking_visitor'),
        ('visitor', '0004_remove_visitor_parking_id_visitor_visitor_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorparking',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors_parkings', to='visitor.visitor'),
        ),
    ]
