# Generated by Django 4.2.7 on 2024-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20),
        ),
    ]
