# Generated by Django 5.1 on 2024-09-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_invoice_deleted_at_invoice_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidhistory',
            name='amount',
        ),
    ]
