# Generated by Django 5.1 on 2024-09-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_paidhistory_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_address',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_city',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_country',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_dob',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_email',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_phone',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_ssn',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_state',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_zip',
        ),
    ]
