# Generated by Django 5.1 on 2024-09-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_remove_card_card_address_remove_card_card_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidhistory',
            name='resident',
        ),
    ]
